# Generated by Django 4.2.7 on 2025-10-02 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("obras", "0001_initial"),
        ("lugares", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Representacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha",
                    models.CharField(
                        help_text="Fecha original del texto", max_length=50
                    ),
                ),
                (
                    "fecha_formateada",
                    models.DateField(
                        blank=True,
                        help_text="Fecha formateada para consultas",
                        null=True,
                    ),
                ),
                (
                    "compañia",
                    models.CharField(
                        blank=True, help_text="Compañía teatral", max_length=200
                    ),
                ),
                (
                    "tipo_lugar",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("palacio", "Palacio"),
                            ("corral", "Corral de comedias"),
                            ("iglesia", "Iglesia"),
                            ("plaza", "Plaza pública"),
                            ("teatro", "Teatro"),
                            ("casa", "Casa particular"),
                            ("universidad", "Universidad"),
                            ("convento", "Convento"),
                            ("otro", "Otro"),
                        ],
                        help_text="Tipo de lugar de representación",
                        max_length=100,
                    ),
                ),
                (
                    "director_compañia",
                    models.CharField(
                        blank=True, help_text="Director de la compañía", max_length=200
                    ),
                ),
                (
                    "fuente",
                    models.CharField(
                        blank=True, help_text="Fuente de la información", max_length=200
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, help_text="Observaciones sobre la representación"
                    ),
                ),
                (
                    "mecenas",
                    models.CharField(
                        blank=True, help_text="Mecenas o patrocinador", max_length=200
                    ),
                ),
                (
                    "gestor_administrativo",
                    models.CharField(
                        blank=True, help_text="Gestor administrativo", max_length=200
                    ),
                ),
                (
                    "tipo_funcion",
                    models.CharField(
                        blank=True,
                        help_text="Tipo de función (fiesta, celebración, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "publico",
                    models.CharField(
                        blank=True,
                        help_text="Tipo de público (corte, pueblo, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "entrada",
                    models.CharField(
                        blank=True,
                        help_text="Información sobre entrada o precio",
                        max_length=100,
                    ),
                ),
                (
                    "duracion",
                    models.CharField(
                        blank=True,
                        help_text="Duración de la representación",
                        max_length=100,
                    ),
                ),
                ("notas", models.TextField(blank=True, help_text="Notas adicionales")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lugar",
                    models.ForeignKey(
                        blank=True,
                        help_text="Lugar de la representación",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="representaciones",
                        to="lugares.lugar",
                    ),
                ),
                (
                    "obra",
                    models.ForeignKey(
                        help_text="Obra representada",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="representaciones",
                        to="obras.obra",
                    ),
                ),
            ],
            options={
                "verbose_name": "Representación",
                "verbose_name_plural": "Representaciones",
                "ordering": ["-fecha_formateada", "obra__titulo_limpio"],
            },
        ),
    ]
