# Generated by Django 4.2.7 on 2025-10-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("representaciones", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="representacion",
            name="pagina_pdf",
            field=models.IntegerField(
                blank=True,
                help_text="Número de página del PDF donde aparece esta representación",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="representacion",
            name="texto_original_pdf",
            field=models.TextField(
                blank=True,
                help_text="Texto original extraído del PDF para esta representación",
            ),
        ),
    ]
