# Generated by Django 4.2.7 on 2025-10-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("representaciones", "0002_representacion_pagina_pdf_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="representacion",
            name="es_anterior_1650",
            field=models.BooleanField(
                default=False, help_text="Si la representación es anterior a 1650"
            ),
        ),
        migrations.AddField(
            model_name="representacion",
            name="es_anterior_1665",
            field=models.BooleanField(
                default=False, help_text="Si la representación es anterior a 1665"
            ),
        ),
        migrations.AddField(
            model_name="representacion",
            name="organizadores_fiesta",
            field=models.TextField(
                blank=True,
                help_text="Nombres propios o títulos de organizadores (Heliche, gremios, etc.)",
            ),
        ),
        migrations.AddField(
            model_name="representacion",
            name="personajes_historicos",
            field=models.TextField(
                blank=True,
                help_text="Menciones de personajes históricos o cargos (nobles, embajadores, etc.)",
            ),
        ),
    ]
