# Generated by Django 4.2.7 on 2025-10-02 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("autores", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Obra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        help_text="Título original de la obra", max_length=500
                    ),
                ),
                (
                    "titulo_limpio",
                    models.CharField(
                        help_text="Título normalizado y limpio",
                        max_length=500,
                        unique=True,
                    ),
                ),
                (
                    "titulo_alternativo",
                    models.CharField(
                        blank=True,
                        help_text="Títulos alternativos o variaciones",
                        max_length=500,
                    ),
                ),
                (
                    "tipo_obra",
                    models.CharField(
                        choices=[
                            ("comedia", "Comedia"),
                            ("auto", "Auto sacramental"),
                            ("zarzuela", "Zarzuela"),
                            ("entremes", "Entremés"),
                            ("tragedia", "Tragedia"),
                            ("loa", "Loa"),
                            ("sainete", "Sainete"),
                            ("baile", "Baile"),
                            ("otro", "Otro"),
                        ],
                        help_text="Tipo de obra teatral",
                        max_length=100,
                    ),
                ),
                (
                    "genero",
                    models.CharField(
                        blank=True, help_text="Género específico", max_length=100
                    ),
                ),
                (
                    "edicion_principe",
                    models.TextField(
                        blank=True, help_text="Información sobre la edición príncipe"
                    ),
                ),
                (
                    "notas_bibliograficas",
                    models.TextField(blank=True, help_text="Notas bibliográficas"),
                ),
                (
                    "fuente_principal",
                    models.CharField(
                        choices=[
                            ("FUENTESXI", "FUENTES XI (Varey & Shergold)"),
                            ("CATCOM", "CATCOM (Base de datos web)"),
                            ("AMBAS", "Ambas fuentes"),
                        ],
                        help_text="Fuente principal de los datos",
                        max_length=50,
                    ),
                ),
                (
                    "tema",
                    models.CharField(
                        blank=True,
                        help_text="Tema principal de la obra",
                        max_length=200,
                    ),
                ),
                (
                    "musica_conservada",
                    models.BooleanField(
                        default=False, help_text="Si se conserva música de la obra"
                    ),
                ),
                (
                    "compositor",
                    models.CharField(
                        blank=True, help_text="Compositor de la música", max_length=200
                    ),
                ),
                (
                    "mecenas",
                    models.CharField(
                        blank=True, help_text="Mecenas o patrocinador", max_length=200
                    ),
                ),
                (
                    "fecha_creacion_estimada",
                    models.CharField(
                        blank=True,
                        help_text="Fecha estimada de creación",
                        max_length=50,
                    ),
                ),
                (
                    "idioma",
                    models.CharField(
                        default="Español", help_text="Idioma de la obra", max_length=50
                    ),
                ),
                (
                    "versos",
                    models.IntegerField(
                        blank=True,
                        help_text="Número de versos (si se conoce)",
                        null=True,
                    ),
                ),
                (
                    "actos",
                    models.IntegerField(
                        blank=True, help_text="Número de actos", null=True
                    ),
                ),
                ("notas", models.TextField(blank=True, help_text="Notas adicionales")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "autor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Autor de la obra",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="obras",
                        to="autores.autor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Obra",
                "verbose_name_plural": "Obras",
                "ordering": ["titulo_limpio"],
            },
        ),
        migrations.CreateModel(
            name="Manuscrito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ubicacion",
                    models.CharField(
                        help_text="Ubicación del manuscrito (biblioteca, archivo, etc.)",
                        max_length=500,
                    ),
                ),
                (
                    "signatura",
                    models.CharField(
                        blank=True,
                        help_text="Signatura o código del manuscrito",
                        max_length=200,
                    ),
                ),
                (
                    "fecha_manuscrito",
                    models.CharField(
                        blank=True, help_text="Fecha del manuscrito", max_length=50
                    ),
                ),
                (
                    "tipo_manuscrito",
                    models.CharField(
                        blank=True,
                        help_text="Tipo de manuscrito (autógrafo, copia, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True, help_text="Descripción del manuscrito"
                    ),
                ),
                ("notas", models.TextField(blank=True, help_text="Notas adicionales")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "obra",
                    models.ForeignKey(
                        help_text="Obra a la que pertenece el manuscrito",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manuscritos",
                        to="obras.obra",
                    ),
                ),
            ],
            options={
                "verbose_name": "Manuscrito",
                "verbose_name_plural": "Manuscritos",
                "ordering": ["ubicacion"],
            },
        ),
    ]
