# Generated by Django 4.2.7 on 2025-10-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obras", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaginaPDF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_pagina",
                    models.IntegerField(
                        help_text="Número de página en el PDF", unique=True
                    ),
                ),
                (
                    "texto_extraido",
                    models.TextField(
                        blank=True, help_text="Texto extraído de esta página"
                    ),
                ),
                (
                    "archivo_imagen",
                    models.CharField(
                        blank=True,
                        help_text="Ruta al archivo de imagen de la página",
                        max_length=500,
                    ),
                ),
                (
                    "part_file",
                    models.CharField(
                        blank=True,
                        help_text="Archivo de texto del que proviene (ej: part_001)",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Página PDF",
                "verbose_name_plural": "Páginas PDF",
                "ordering": ["numero_pagina"],
            },
        ),
        migrations.AddField(
            model_name="obra",
            name="origen_datos",
            field=models.CharField(
                choices=[("web", "Web"), ("pdf", "PDF"), ("manual", "Manual")],
                default="web",
                help_text="Origen de los datos (web, pdf, manual)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="obra",
            name="pagina_pdf",
            field=models.IntegerField(
                blank=True,
                help_text="Número de página del PDF donde aparece la información",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="obra",
            name="texto_original_pdf",
            field=models.TextField(
                blank=True, help_text="Texto original extraído del PDF para esta obra"
            ),
        ),
    ]
