# Generated by Django 4.2.7 on 2025-10-02 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("obras", "0002_paginapdf_obra_origen_datos_obra_pagina_pdf_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ObraTema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "es_principal",
                    models.BooleanField(
                        default=False, help_text="Si es el tema principal de la obra"
                    ),
                ),
                (
                    "notas",
                    models.TextField(
                        blank=True, help_text="Notas sobre la relación obra-tema"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "obra",
                    models.ForeignKey(
                        help_text="Obra teatral",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="obras.obra",
                    ),
                ),
            ],
            options={
                "verbose_name": "Relación Obra-Tema",
                "verbose_name_plural": "Relaciones Obra-Tema",
                "ordering": ["-es_principal", "tema__nombre"],
            },
        ),
        migrations.CreateModel(
            name="TemaLiterario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre del tema literario",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "tipo_tema",
                    models.CharField(
                        choices=[
                            ("mitologico", "Mitológico"),
                            ("historico", "Histórico"),
                            ("religioso", "Religioso"),
                            ("comico", "Cómico"),
                            ("tragico", "Trágico"),
                            ("pastoral", "Pastoral"),
                            ("caballeresco", "Caballeresco"),
                            ("costumbrista", "Costumbrista"),
                            ("moral", "Moral"),
                            ("politico", "Político"),
                            ("amoroso", "Amoroso"),
                            ("otro", "Otro"),
                        ],
                        help_text="Tipo de tema literario",
                        max_length=50,
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, help_text="Descripción del tema"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "obras",
                    models.ManyToManyField(
                        help_text="Obras que pertenecen a este tema",
                        related_name="temas_literarios",
                        through="obras.ObraTema",
                        to="obras.obra",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tema Literario",
                "verbose_name_plural": "Temas Literarios",
                "ordering": ["tipo_tema", "nombre"],
            },
        ),
        migrations.AddField(
            model_name="obratema",
            name="tema",
            field=models.ForeignKey(
                help_text="Tema literario",
                on_delete=django.db.models.deletion.CASCADE,
                to="obras.temaliterario",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="obratema",
            unique_together={("obra", "tema")},
        ),
    ]
