# Generated by Django 4.2.7 on 2025-10-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obras", "0003_obratema_temaliterario_obratema_tema_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="obra",
            name="bibliografia_musica",
            field=models.TextField(
                blank=True, help_text="Bibliografía moderna sobre la música"
            ),
        ),
        migrations.AddField(
            model_name="obra",
            name="bibliotecas_musica",
            field=models.TextField(
                blank=True, help_text="Bibliotecas donde se conserva la música"
            ),
        ),
        migrations.AddField(
            model_name="obra",
            name="ediciones_conocidas",
            field=models.TextField(
                blank=True, help_text="Ediciones conocidas de la obra"
            ),
        ),
        migrations.AddField(
            model_name="obra",
            name="manuscritos_conocidos",
            field=models.TextField(
                blank=True, help_text="Manuscritos conocidos de la obra"
            ),
        ),
    ]
