# Generated by Django 4.2.7 on 2025-10-02 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("obras", "0004_obra_bibliografia_musica_obra_bibliotecas_musica_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="manuscrito",
            options={
                "ordering": ["biblioteca", "signatura"],
                "verbose_name": "Manuscrito",
                "verbose_name_plural": "Manuscritos",
            },
        ),
        migrations.AlterModelOptions(
            name="obratema",
            options={
                "ordering": ["-es_principal", "tema__nombre"],
                "verbose_name": "Obra-Tema",
                "verbose_name_plural": "Obras-Temas",
            },
        ),
        migrations.AlterModelOptions(
            name="temaliterario",
            options={
                "ordering": ["nombre"],
                "verbose_name": "Tema Literario",
                "verbose_name_plural": "Temas Literarios",
            },
        ),
        migrations.RemoveField(
            model_name="manuscrito",
            name="tipo_manuscrito",
        ),
        migrations.RemoveField(
            model_name="manuscrito",
            name="ubicacion",
        ),
        migrations.RemoveField(
            model_name="temaliterario",
            name="obras",
        ),
        migrations.RemoveField(
            model_name="temaliterario",
            name="tipo_tema",
        ),
        migrations.AddField(
            model_name="manuscrito",
            name="biblioteca",
            field=models.CharField(
                default="", help_text="Biblioteca donde se conserva", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="obra",
            name="observaciones",
            field=models.TextField(blank=True, help_text="Observaciones generales"),
        ),
        migrations.AddField(
            model_name="obratema",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="manuscrito",
            name="signatura",
            field=models.CharField(
                help_text="Signatura del manuscrito", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="obra",
            name="bibliografia_musica",
            field=models.TextField(
                blank=True, help_text="Bibliografía sobre la música"
            ),
        ),
        migrations.AlterField(
            model_name="obra",
            name="ediciones_conocidas",
            field=models.TextField(blank=True, help_text="Ediciones conocidas"),
        ),
        migrations.AlterField(
            model_name="obra",
            name="fecha_creacion_estimada",
            field=models.CharField(
                blank=True, help_text="Fecha estimada de creación", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="obra",
            name="idioma",
            field=models.CharField(
                default="español", help_text="Idioma de la obra", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="obra",
            name="manuscritos_conocidos",
            field=models.TextField(blank=True, help_text="Manuscritos conocidos"),
        ),
        migrations.AlterField(
            model_name="obra",
            name="versos",
            field=models.IntegerField(
                blank=True, help_text="Número de versos", null=True
            ),
        ),
        migrations.AlterField(
            model_name="obratema",
            name="obra",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="obratema_set",
                to="obras.obra",
            ),
        ),
        migrations.AlterField(
            model_name="obratema",
            name="tema",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="obras",
                to="obras.temaliterario",
            ),
        ),
        migrations.CreateModel(
            name="ComentarioUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "catalogo",
                    models.CharField(
                        choices=[("fuentesxi", "FUENTES XI"), ("catcom", "CATCOM")],
                        help_text="Catálogo al que pertenece la selección",
                        max_length=50,
                    ),
                ),
                (
                    "titulo",
                    models.CharField(help_text="Título del comentario", max_length=200),
                ),
                ("comentario", models.TextField(help_text="Contenido del comentario")),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha de creación del comentario"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, help_text="Fecha de última modificación"
                    ),
                ),
                (
                    "es_publico",
                    models.BooleanField(
                        default=False,
                        help_text="Si el comentario es visible para otros usuarios",
                    ),
                ),
                (
                    "obras_seleccionadas",
                    models.ManyToManyField(
                        help_text="Obras seleccionadas para el comentario",
                        related_name="comentarios_usuario",
                        to="obras.obra",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        help_text="Usuario que hizo el comentario",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comentarios",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Comentario de Usuario",
                "verbose_name_plural": "Comentarios de Usuario",
                "ordering": ["-fecha_creacion"],
            },
        ),
    ]
