# Generated by Django 4.2.7 on 2025-10-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obras", "0005_alter_manuscrito_options_alter_obratema_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="obra",
            name="subgenero",
            field=models.CharField(
                blank=True,
                help_text="Subgénero o clasificación más específica",
                max_length=100,
            ),
        ),
    ]
