# Generated by Django 4.2.7 on 2025-10-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obras", "0006_add_subgenero_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="comentariousuario",
            name="etiqueta_ia",
            field=models.BooleanField(
                default=False,
                help_text="Marcar para exportar y usar con IA en análisis de catálogos",
            ),
        ),
    ]
