# Generated by Django 4.2.7 on 2026-03-19 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('obras', '0007_add_etiqueta_ia_to_comentarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropuestaCambioObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(max_length=100)),
                ('valor_anterior', models.TextField(blank=True, default='')),
                ('valor_nuevo', models.TextField(blank=True, default='')),
                ('comentario', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada_superuser', 'Aprobada por superusuario'), ('rechazada', 'Rechazada')], default='pendiente', max_length=30)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propuestas_cambio', to='obras.obra')),
                ('propuesta_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propuestas_creadas', to=settings.AUTH_USER_MODEL)),
                ('resuelta_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propuestas_resueltas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Propuesta de cambio de obra',
                'verbose_name_plural': 'Propuestas de cambio de obra',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='VotoPropuestaCambioObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto', models.CharField(choices=[('a_favor', 'A favor'), ('en_contra', 'En contra')], max_length=20)),
                ('comentario', models.TextField(blank=True, default='')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('propuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='obras.propuestacambioobra')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos_propuesta_obra', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voto de propuesta de cambio',
                'verbose_name_plural': 'Votos de propuesta de cambio',
                'ordering': ['-fecha_creacion'],
                'unique_together': {('propuesta', 'usuario')},
            },
        ),
    ]
