# Generated by Django 4.2.7 on 2026-03-19 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('obras', '0008_propuestacambioobra_votopropuestacambioobra'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentariousuario',
            name='filtros_busqueda',
            field=models.JSONField(blank=True, help_text='JSON con filtros de búsqueda guardados desde el frontend', null=True),
        ),
        migrations.AddField(
            model_name='comentariousuario',
            name='tipo',
            field=models.CharField(blank=True, default='comentario', help_text='Tipo de comentario (p.ej. comentario / comentario_general)', max_length=50),
        ),
        migrations.AddField(
            model_name='comentariousuario',
            name='visto_at',
            field=models.DateTimeField(blank=True, help_text='Fecha en que el admin marcó el comentario como visto', null=True),
        ),
        migrations.AddField(
            model_name='comentariousuario',
            name='visto_por',
            field=models.ForeignKey(blank=True, help_text='Admin que marcó el comentario como visto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios_vistos_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comentariousuario',
            name='visto_por_admin',
            field=models.BooleanField(default=False, help_text='Indica si el admin ya ha revisado el comentario'),
        ),
    ]
