# Generated by Django 4.2.7 on 2025-10-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Autor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(help_text="Nombre del autor", max_length=200),
                ),
                (
                    "nombre_completo",
                    models.CharField(
                        blank=True,
                        help_text="Nombre completo del autor",
                        max_length=300,
                    ),
                ),
                (
                    "fecha_nacimiento",
                    models.CharField(
                        blank=True,
                        help_text="Fecha de nacimiento (formato original)",
                        max_length=50,
                    ),
                ),
                (
                    "fecha_muerte",
                    models.CharField(
                        blank=True,
                        help_text="Fecha de muerte (formato original)",
                        max_length=50,
                    ),
                ),
                (
                    "biografia",
                    models.TextField(blank=True, help_text="Biografía del autor"),
                ),
                (
                    "obras_principales",
                    models.TextField(
                        blank=True, help_text="Lista de obras principales"
                    ),
                ),
                (
                    "epoca",
                    models.CharField(
                        blank=True,
                        help_text="Época histórica (ej: Siglo de Oro)",
                        max_length=100,
                    ),
                ),
                (
                    "notas",
                    models.TextField(
                        blank=True, help_text="Notas adicionales sobre el autor"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Autor",
                "verbose_name_plural": "Autores",
                "ordering": ["nombre"],
            },
        ),
    ]
