# Generated by Django 4.2.7 on 2025-10-02 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("obras", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferenciaBibliografica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        help_text="Título de la referencia", max_length=500
                    ),
                ),
                (
                    "autor",
                    models.CharField(
                        blank=True, help_text="Autor de la referencia", max_length=300
                    ),
                ),
                (
                    "editor",
                    models.CharField(
                        blank=True, help_text="Editor o compilador", max_length=300
                    ),
                ),
                (
                    "lugar_publicacion",
                    models.CharField(
                        blank=True, help_text="Lugar de publicación", max_length=200
                    ),
                ),
                (
                    "año_publicacion",
                    models.CharField(
                        blank=True, help_text="Año de publicación", max_length=50
                    ),
                ),
                (
                    "paginas",
                    models.CharField(
                        blank=True,
                        help_text="Páginas o rango de páginas",
                        max_length=100,
                    ),
                ),
                (
                    "tipo_referencia",
                    models.CharField(
                        choices=[
                            ("libro", "Libro"),
                            ("articulo", "Artículo"),
                            ("tesis", "Tesis"),
                            ("manuscrito", "Manuscrito"),
                            ("edicion", "Edición"),
                            ("catalogo", "Catálogo"),
                            ("base_datos", "Base de datos"),
                            ("web", "Recurso web"),
                            ("otro", "Otro"),
                        ],
                        help_text="Tipo de referencia",
                        max_length=100,
                    ),
                ),
                (
                    "url",
                    models.URLField(blank=True, help_text="URL si es un recurso web"),
                ),
                (
                    "isbn",
                    models.CharField(
                        blank=True, help_text="ISBN si es un libro", max_length=20
                    ),
                ),
                (
                    "issn",
                    models.CharField(
                        blank=True, help_text="ISSN si es una revista", max_length=20
                    ),
                ),
                (
                    "doi",
                    models.CharField(
                        blank=True, help_text="DOI si está disponible", max_length=100
                    ),
                ),
                (
                    "volumen",
                    models.CharField(
                        blank=True, help_text="Volumen o tomo", max_length=50
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        blank=True,
                        help_text="Número de revista o publicación",
                        max_length=50,
                    ),
                ),
                (
                    "revista",
                    models.CharField(
                        blank=True, help_text="Nombre de la revista", max_length=200
                    ),
                ),
                (
                    "editorial",
                    models.CharField(blank=True, help_text="Editorial", max_length=200),
                ),
                (
                    "coleccion",
                    models.CharField(
                        blank=True, help_text="Colección o serie", max_length=200
                    ),
                ),
                ("notas", models.TextField(blank=True, help_text="Notas adicionales")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "obra",
                    models.ForeignKey(
                        help_text="Obra a la que se refiere",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referencias_bibliograficas",
                        to="obras.obra",
                    ),
                ),
            ],
            options={
                "verbose_name": "Referencia Bibliográfica",
                "verbose_name_plural": "Referencias Bibliográficas",
                "ordering": ["autor", "año_publicacion"],
            },
        ),
    ]
