# Generated by Django 4.2.7 on 2025-10-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lugar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(help_text="Nombre del lugar", max_length=200),
                ),
                (
                    "coordenadas_lat",
                    models.FloatField(blank=True, help_text="Latitud", null=True),
                ),
                (
                    "coordenadas_lng",
                    models.FloatField(blank=True, help_text="Longitud", null=True),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True, help_text="Región o provincia", max_length=200
                    ),
                ),
                (
                    "pais",
                    models.CharField(
                        default="España", help_text="País", max_length=100
                    ),
                ),
                (
                    "tipo_lugar",
                    models.CharField(
                        choices=[
                            ("palacio", "Palacio"),
                            ("corral", "Corral de comedias"),
                            ("iglesia", "Iglesia"),
                            ("plaza", "Plaza pública"),
                            ("teatro", "Teatro"),
                            ("casa", "Casa particular"),
                            ("universidad", "Universidad"),
                            ("convento", "Convento"),
                            ("otro", "Otro"),
                        ],
                        help_text="Tipo de lugar",
                        max_length=100,
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, help_text="Descripción del lugar"),
                ),
                (
                    "poblacion_estimada",
                    models.IntegerField(
                        blank=True,
                        help_text="Población estimada en el siglo XVII",
                        null=True,
                    ),
                ),
                (
                    "es_capital",
                    models.BooleanField(
                        default=False, help_text="Si es capital de región o país"
                    ),
                ),
                (
                    "notas_historicas",
                    models.TextField(
                        blank=True, help_text="Notas históricas sobre el lugar"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Lugar",
                "verbose_name_plural": "Lugares",
                "ordering": ["nombre"],
                "unique_together": {("nombre", "region")},
            },
        ),
    ]
